<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>PinWindow</AssemblyName>
    <RootNamespace>PinWindow</RootNamespace>
    <Version>3.3.0</Version>
    <Authors>helliong</Authors>
    <Description>Закрепление активного окна поверх остальных с помощью кнопки в заголовке или горячей клавиши.</Description>
  </PropertyGroup>
</Project>
